title: Spinorama
logo: /logo.jpg
description: Spinorama is a collection of speaker measurements. You can also easily compare them, find similar speakers or find a EQ that will make them sound better.
show_dowloads: false
theme: jekyll-theme-minimal
